- name: Start service docker, if not started
  service:
    name: docker
    state: started
    enabled: yes

- name: Run node_exporter container
  community.docker.docker_container:
    name: node_exporter
    image: "{{ exporter_image_name }}:{{ exporter_image_version }}"   
    state: started
    restart_policy: always
    pid_mode: host
    network_mode: host
    volumes:
      - "/:/host:ro"
    command: >
      --path.rootfs /host --web.listen-address=":9889"
