- name: Install MongoDB
  include_tasks: install.yml
  when: "'install' in action_env"

- name: Configure MongoDB
  include_tasks: config.yml
  when: "'config' in action_env or 'install' in action_env"

- name: Manage MongoDB service
  include_tasks: service.yml
  when: "'install' in action_env"

- name: Configure Rotate Logs
  include_tasks: rotate_config.yml
  when: "'rotate' in action_env or 'install' in action_env"

- name: Uninstall MongoDB
  include_tasks: uninstall.yml
  when: "'uninstall' in action_env"
