# Include OS-specific variables
- name: Include OS-specific variables
  include_vars: "{{ mongodb_os_family }}.yml"
  failed_when: mongodb_os_family not in ['Debian', 'RedHat']

# Core installation and configuration
- name: Mongodb installation
  import_tasks: install.yml

- name: Config security
  import_tasks: security.yml

- name: Mongodb Configuration
  import_tasks: configure.yml

# Deployment-specific configuration
- name: Deploy standalone mode
  import_tasks: deployment/standalone.yml
  when: mongodb_deployment_mode == "standalone"

- name: Deploy replica_set mode
  import_tasks: deployment/replica_set.yml
  when:
    - mongodb_deployment_mode == "replica_set"

- name: Deploy sharded_cluster mode
  import_tasks: deployment/sharded_cluster.yml
  when: mongodb_deployment_mode == "sharded_cluster"

- name: Final validation
  import_tasks: validate.yml
