---
- name: Check if cluster UUID exists
  stat:
    path: "{{ kafka_home }}/cluster-uuid"
  register: uuid_file

- name: Generate cluster UUID
  shell: "{{ kafka_home }}/bin/kafka-storage.sh random-uuid"
  register: cluster_uuid_output
  when: not uuid_file.stat.exists

- name: Save cluster UUID
  copy:
    content: "{{ cluster_uuid_output.stdout }}"
    dest: "{{ kafka_home }}/cluster-uuid"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
  when: not uuid_file.stat.exists

- name: Read cluster UUID
  slurp:
    src: "{{ kafka_home }}/cluster-uuid"
  register: cluster_uuid_file

- name: Set cluster UUID fact
  set_fact:
    kafka_cluster_uuid: "{{ cluster_uuid_file.content | b64decode | trim }}"

