# Inventory
[common-host]
10.9.24.95 hostname=datnguyen-poc-gce-01-001

# Role
[playbooks]
mongodb

# Variables
[all:vars]
# env can only be dev, uat or prod. This is requirement for wazuh and metric register
env = "dev"
# set timezone for OS
timezone = "Asia/Ho_Chi_Minh"
# mount attached disk
mount_attached_disk = true
attached_disk = "/dev/sdb"
mount_point = "/mnt/data"
deployment_mode="standalone"
mongo_version="6.0.5"
