; # Inventory
; [es]
; 34.45.189.93 hostname=vm-instance-1 elasticsearch_node_roles=['master'] elasticsearch_rack_id=rack-1
; 34.132.226.224 hostname=vm-instance-2 elasticsearch_node_roles=['master'] elasticsearch_rack_id=rack-2
; 35.184.50.227 hostname=vm-instance-3 elasticsearch_node_roles=['master'] elasticsearch_rack_id=rack-3
;
; # Role
; [playbooks]
; elasticsearch
;
; # Variables
; [all:vars]
; deployment_mode=cluster
; elasticsearch_cluster_name=production-cluster
; elasticsearch_heap_size='512m'


; # Inventory
; [common-host]
; 34.45.189.93 hostname=vm-instance-1
; 34.132.226.224 hostname=vm-instance-2
; 35.184.50.227 hostname=vm-instance-3
;
; # Role
; [playbooks]
; vm_initial
;
; # Variables
; [all:vars]
; # env can only be dev, uat or prod. This is requirement for wazuh and metric register
; env = "dev"
; # set timezone for OS
; timezone = "Asia/Ho_Chi_Minh"
; # mount attached disk
; mount_attached_disk = false
; attached_disk = "/dev/sdb"
; mount_point = "/mnt/data"
;

[zk]
34.45.189.93 hostname=vm-instance-1 zookeeper_id=1

[kfk]
34.45.189.93 hostname=vm-instance-1 broker_id=1
34.132.226.224 hostname=vm-instance-2 broker_id=2

# Role
[playbooks]
kafka

[all:vars]
# System Configuration
kafka_user = "kafka"
kafka_group = "kafka"
kafka_home = "/var/lib/kafka"

# Java Configuration
java_version = "11"

# Zookeeper Configuration
zookeeper_version = "3.8.3"
zookeeper_port = 2181
zookeeper_peer_port = 2888
zookeeper_leader_port = 3888
zookeeper_data_dir = "{{ data_dir }}/zookeeper"
zookeeper_log_dir = "/var/log/zookeeper"
zookeeper_max_client_cnxns = 60
zookeeper_autopurge_purgeinterval = 1
zookeeper_autopurge_snapretaincount = 10
