# Inventory
; [common-host]
; 34.45.189.93 hostname=vm-instance-1
; 34.132.226.224 hostname=vm-instance-2
; 35.184.50.227 hostname=vm-instance-3
;
; # Role
; [playbooks]
; vm_initial
;
; # Variables
; [all:vars]
; # env can only be dev, uat or prod. This is requirement for wazuh and metric register
; env = "dev"
; # set timezone for OS
; timezone = "Asia/Ho_Chi_Minh"
; # mount attached disk
; mount_attached_disk = false
; attached_disk = "/dev/sdb"
; mount_point = "/mnt/data"
;

[kraft]
34.45.189.93 hostname=vm-instance-1 kafka_node_id=0 kafka_roles="controller,broker"

[kfk]
34.45.189.93 hostname=vm-instance-1 kafka_node_id=0 kafka_roles="controller,broker"
34.132.226.224 hostname=vm-instance-2 kafka_node_id=0 kafka_roles="broker"

# Role
[playbooks]
kafka

[all:vars]
# System Configuration
kafka_version = "2.13-3.9.1"
kafka_user = "kafka"
kafka_group = "kafka"
kafka_home = "/var/lib/kafka"
data_dir = "/mnt/data"
kafka_mode = kraft

# Java Configuration
java_version = "11"
