[es]
34.45.189.93 hostname=vm-instance-1 elasticsearch_node_roles=['master'] elasticsearch_rack_id=rack-1

# Role
[playbooks]
elasticsearch
elasticsearch_exporter

[all:vars]
deployment_mode=single-node
elasticsearch_cluster_name=dev-cluster
elasticsearch_heap_size=2g
