[kraft]
34.45.189.93 hostname=vm-instance-1 kafka_node_id=0 kafka_roles="controller,broker"
35.184.50.227 hostname=vm-instance-3 kafka_node_id=2 kafka_roles="controller,broker"
[kfk]
34.45.189.93 hostname=vm-instance-1 kafka_node_id=0 kafka_roles="controller,broker"
34.132.226.224 hostname=vm-instance-2 kafka_node_id=1 kafka_roles="broker"
35.184.50.227 hostname=vm-instance-2 kafka_node_id=2 kafka_roles="controller,broker"

# Role
[playbooks]
kafka_kraft

[all:vars]
# System Configuration
kafka_version = "2.13-3.9.1"
kafka_user = "kafka"
kafka_group = "kafka"
kafka_home = "/opt/kafka"
data_dir = "/mnt/data"
kafka_mode = kraft

# Java Configuration
java_version = "11"
