#Note: if 1 zk or kfk will install single node mode
[zk]
34.45.189.93 hostname=vm-instance-1 zookeeper_id=1

[kfk]
34.45.189.93 hostname=vm-instance-1 broker_id=1
34.132.226.224 hostname=vm-instance-2 broker_id=2

# Role
[playbooks]
kafka

[all:vars]
# System Configuration
kafka_user = "kafka"
kafka_group = "kafka"
kafka_home = "/var/lib/kafka"

# Java Configuration
java_version = "11"

# Zookeeper Configuration
zookeeper_version = "3.8.3"
zookeeper_port = 2181
zookeeper_peer_port = 2888
zookeeper_leader_port = 3888
zookeeper_data_dir = "{{ data_dir }}/zookeeper"
zookeeper_log_dir = "/var/log/zookeeper"
zookeeper_max_client_cnxns = 60
zookeeper_autopurge_purgeinterval = 1
zookeeper_autopurge_snapretaincount = 10
