[mongodb_replica_set]
30.9.24.99 hostname=mongodb-001 member_priority=1
30.9.24.100 hostname=mongodb-002 member_priority=1
30.9.24.101 hostname=mongodb-003 member_priority=1

# Role
[playbooks]
mongodb

# Variables
[all:vars]
#deployment_mode should be standalone, replica_set, sharded_cluster
deployment_mode="replica_set"
# should be declare
mongo_version="6.0.5"
# must be declare password
mongodb_root_admin_password="SecurePassword123"
# must be declare when deployment_mode is replica_set/sharded_cluster
mongodb_keyfile_content="laughing6901"
