# Inventory
[common-host]
10.9.24.95 hostname=datnguyen-poc-gce-01-001

# Role
[playbooks]
mongodb

# Variables
[all:vars]
#deployment_mode should be standalone, replica_set, sharded_cluster
deployment_mode="standalone"
# should be declare
mongo_version="6.0.5"
# must be declare password
mongodb_root_admin_password="SecurePassword123!"
# must be declare when deployment_mode is replica_set/sharded_cluster
mongodb_keyfile_content="laughing6901"

# you can custom all variables here. To see variables please go to /roles/mongodb/defaults/main.yml
