# |    Role       | Persistence	 | maxmemory-policy	      | Use case          |
# |---------------|--------------|------------------------|-------------------|
# | Cache	        | Off	         | allkeys-lru	          | API cache, token  |
# | Persistent DB |	On (RDB/AOF) | (thường 0 = unlimited) | Queue, leaderboard|
# | Broker	      | Off (thường) | noeviction	            | Pub/Sub, MQ       |
# | Session Store	| Off	         | volatile-lru	          | User session, auth|
