---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart elasticsearch single
  systemd:
    name: "{{ elasticsearch_service_name }}"
    state: restarted
    daemon_reload: true
  when: elasticsearch_deployment_mode == 'single-node'

- name: restart elasticsearch cluster
  systemd:
    name: "{{ elasticsearch_service_name }}"
    state: restarted
    daemon_reload: true
