---
- name: Configure Kafka server properties
  template:
    src: server.properties.j2
    dest: "{{ kafka_home }}/config/server.properties"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0644'
    backup: true
  notify: restart kafka

- name: Configure Kafka log4j properties
  template:
    src: log4j.properties.j2
    dest: "{{ kafka_home }}/config/log4j.properties"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0644'
  notify: restart kafka

- name: Create Kafka systemd service
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
    mode: '0644'
  notify:
    - reload systemd
    - restart kafka
