---
# Core installation and configuration
- name: Kafka installation
  import_tasks: install.yml

- name: Configure Kafka
  include_tasks: configure.yml

# - name: Wait for Kafka to be ready
#   wait_for:
#     port: "{{ kafka_port }}"
#     host: "{{ ansible_host }}"
#     delay: 15
#     timeout: 120

- name: Verify Kafka is running
  command: /opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:{{ kafka_port }}
  register: kafka_status
  changed_when: false
  retries: 2
  delay: 10
