---
elasticsearch_packages:
  - elasticsearch-{{ elasticsearch_version }}
  - java-21-openjdk
  - curl

elasticsearch_repo_baseurl: "https://artifacts.elastic.co/packages/8.x/yum"
elasticsearch_repo_gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"

elasticsearch_user: elasticsearch
elasticsearch_group: elasticsearch
elasticsearch_service_name: elasticsearch
elasticsearch_config_file: "{{ elasticsearch_config_dir }}/elasticsearch.yml"

# RedHat-specific paths
elasticsearch_java_home: "/usr/lib/jvm/java-21-openjdk"
ansible_java_version: 21
elasticsearch_systemd_dir: "/etc/systemd/system"
elasticsearch_systemd_override_dir: "/etc/systemd/system/elasticsearch.service.d"

# Package manager commands
elasticsearch_package_manager: yum
elasticsearch_update_cache: no
