---
- name: Check if storage is already formatted
  stat:
    path: "{{ kafka_log_dirs }}/meta.properties"
  register: storage_formatted

- name: Format Kafka storage for KRaft
  shell: |
    {{ kafka_home }}/bin/kafka-storage.sh format \
    -t {{ kafka_cluster_uuid }} \
    -c {{ kafka_config_dir }}/server.properties \
    --ignore-formatted
  become_user: "{{ kafka_user }}"
  when: not storage_formatted.stat.exists or kraft_format_storage
  notify: restart kafka
