---
- name: Create Zookeeper myid file (multi-node only)
  template:
    src: myid.j2
    dest: "{{ zookeeper_data_dir }}/myid"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0644'
  when:
    - inventory_hostname in groups['zk']
    - groups['zk']|length > 1
  notify: restart zookeeper

- name: Configure Zookeeper
  template:
    src: zoo.cfg.j2
    dest: /opt/zookeeper/conf/zoo.cfg
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0644'
    backup: true
  notify: restart zookeeper

- name: Configure Zookeeper logging
  template:
    src: log4j.properties.j2
    dest: /opt/zookeeper/conf/log4j.properties
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0644'
  notify: restart zookeeper

- name: Create Zookeeper systemd service
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    mode: '0644'
  notify:
    - reload systemd
    - restart zookeeper
