---
# Core installation and configuration
- name: Zookeeper installation
  import_tasks: install.yml

- name: Configure Zookeeper
  include_tasks: configure.yml

- name: Start and enable Zookeeper
  systemd:
    name: zookeeper
    state: started
    enabled: true
    daemon_reload: true
