- name: Check docker is installed
  shell: docker ps
  ignore_errors: yes
  register: docker_installed

- block:
  - name: Install dependencies packages
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  
  - name: Add Docker’s official GPG key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  
  - name: Add docker repository
    apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
      state: present
      update_cache: yes

  - name: Install Docker-ce
    apt:
      name: "{{ 'docker-ce=' + docker_ce_version if docker_ce_version is defined else 'docker-ce' }}"
      state: present
  when: docker_installed.rc != 0

- name: Start service docker, if not started
  service:
    name: docker
    state: started
    enabled: yes
