- name: Create application database
  postgresql_db:
    name: "{{ postgres_database }}"
    owner: "{{ postgres_user }}"
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    state: present
    login_user: postgres
