---
- name: Install and configure Kafka cluster with Zookeeper
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - kafka-common

- name: Configure Zookeeper cluster
  hosts: zk
  become: yes
  serial: "{{ '100%' if groups['zk']|length == 1 else '1' }}"
  roles:
    - kafka-zookeeper
  when: groups['zk'] is defined and groups['zk']|length > 0

- name: Configure Kafka cluster
  hosts: kfk
  become: true
  serial: "{{ '100%' if groups['kfk']|length == 1 else '1' }}"
  roles:
    - kafka

- name: Configure Kafka cluster (KRaft mode)
  hosts: kfk
  become: true
  serial: "{{ '100%' if groups['kfk']|length == 1 else '1' }}"
  roles:
    - kafka-kraft
  when: groups['zk'] is not defined or groups['zk']|length == 0
