---
- name: Install and configure Kafka cluster with Zookeeper
  hosts: all
  become: true
  gather_facts: true
  roles:
    - kafka-common

- name: Configure Zookeeper cluster
  hosts: zk
  become: yes
  serial: "{{ '100%' if groups['zk']|length == 1 else '1' }}"
  roles:
    - kafka-zookeeper

- name: Configure Kafka cluster
  hosts: kfk
  become: true
  serial: "{{ '100%' if groups['kfk']|length == 1 else '1' }}"
  roles:
    - kafka
