- name: Deploy MongoDB
  hosts: all
  become: true
  vars:
    mongodb_deployment_mode: "{{ deployment_mode | default('standalone') }}"
    mongodb_version: "{{ mongo_version | default('6.0.5') }}"
    mongodb_os_family: "{{ ansible_os_family }}"
  roles:
    - role: mongodb
