- name: Install and configure exporter for MongoDB
  hosts: all
  become: yes
  roles:
    - postgres-exporter

- name: Register to metric server
  hosts: all
  become: yes
  roles:
    - metric-register
  vars:
    consul_service_name: "postgres"
    consul_service_port:  "9187"
