---
- name: Deploy Redis Standalone or Cluster
  hosts: redis
  become: true
  gather_facts: true
  roles:
    - redis
  vars:
    # Deployment mode: "standalone" hoặc "cluster"
    redis_deployment_mode: "{{ deployment_mode | default('standalone') }}"
